language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly
dist: xenial
services:
  - xvfb
addons:
  apt:
    packages:
    - libgconf-2-4
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Electron")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
